version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017" # Expose MongoDB on the host machine
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  backend:
    build:
      context: ./backend # Directory where the Go backend Dockerfile is located
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: mongodb://root:example@mongodb:27017/mydatabase # MongoDB URI with database name included
      DB_NAME: mydatabase
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend # Directory where the React frontend Dockerfile is located
    container_name: frontend
    ports:
      - "3000:80" # Expose the frontend on host port 3000
    depends_on:
      - backend
